// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeckProductsApp.Data;

#nullable disable

namespace PeckProductsApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeckProductsApp.Models.ProdutoPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeUnidades")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("ProdutoPacks");
                });

            modelBuilder.Entity("PeckProductsApp.Models.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProdutoPackId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoPackId");

                    b.ToTable("Sabores");
                });

            modelBuilder.Entity("PeckProductsApp.Models.Sabor", b =>
                {
                    b.HasOne("PeckProductsApp.Models.ProdutoPack", "ProdutoPack")
                        .WithMany("Sabores")
                        .HasForeignKey("ProdutoPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoPack");
                });

            modelBuilder.Entity("PeckProductsApp.Models.ProdutoPack", b =>
                {
                    b.Navigation("Sabores");
                });
#pragma warning restore 612, 618
        }
    }
}
